### ISSUE TITLE
The game crash

### ISSUE THREAD

**Issue by Produktecheck** [juancarloscp52/Entropy#1]
The game crash

**Comment by juancarloscp52** [comment]
Hi! I'll need a little bit more information in order to understand what has happened. Do you have Fabric Api Installed?, What other mods have you installed? Please, send a copy of the crashlog in order to check were the fail occurs ;)

**Comment by Produktecheck** [comment]
ok

**Comment by alexei4884** [comment]
delete optifine and optifabric. Also, you can change the render distance.

download sodium instead of optfine.
