### ISSUE TITLE
Game crach when starting a world

### ISSUE THREAD

**Issue by SH4DOW4RE** [juancarloscp52/Entropy#124]
I'm trying to start a world using Entopy mod and other mods, as well as with a randomizer datapack, and the game refuses to start the world with the error 
```
Encountered exception while handling in channel with name "entropy:join-handshake"
java.lang.NullPointerException: Cannot read field "currentEvents" because "this.eventHandler" is null
```

[latest.log and regular log (Gist)](https://gist.github.com/SH4DOW4RE/ae9dd18717ce8c8a12081d7af1fbe07a)

**Comment by bl4ckscor3** [comment]
[This](https://github.com/juancarloscp52/Entropy/blob/1.19.4/src/main/java/me/juancarloscp52/entropy/Entropy.java#L92) is the line that's crashing, because in line 87 the check failed as there were not exactly one players on the server. I wonder if there is a reason the check isn't just a simple null check.

**Comment by SH4DOW4RE** [comment]
Do you have any idea how I could solve this, or is it an issue in the mod itself ?

**Comment by bl4ckscor3** [comment]
Since this is singleplayer, I only have the idea of removing mods until the world starts. There might be a mod that causes that code to run too early. The problem is that Entropy seems to only initialize when exactly one player is present. Otherwise it'll crash like you're experiencing.

**Comment by SH4DOW4RE** [comment]
I'll try to start with only fabric api and entropy and see if I get the issue again when I get home in a bit. I'll keep you updated

**Comment by SH4DOW4RE** [comment]
Good news, with only Entropy and Fabric API it loaded a world perfectly, and I saw the timer bar going, so one of the mods I have is causing the issue.

**Comment by SH4DOW4RE** [comment]
Okay, so the mod that was causing problems was the helper mod from a Minecraft Randomizer (https://fasguy.net/minecraft_toolbox/loot-table-randomizer). Now the mod works perfectly, thank you for your help.
