### ISSUE TITLE
Discord bots won't work.

### ISSUE THREAD

**Issue by NatTheMatt** [juancarloscp52/Entropy#9]
I followed the tutorial, and I was able to a bot that works but now I can't make a new one.

**Comment by DrewniokYT** [comment]
You too?

**Comment by DrewniokYT** [comment]
My bot is just always offline

**Comment by NatTheMatt** [comment]
Yea. I'm not sure if it's an issue with the mod or discord.

**Comment by NatTheMatt** [comment]
Ok so now the bot that worked doesn't anymore. It might be discord.

**Comment by juancarloscp52** [comment]
Hi! sorry for the delay. The issue has been fixed in the last version of entropy. Please re-enter your discord tokens on the mod
